from __future__ import annotations

from dataclasses import asdict, is_dataclass
from typing import Any, Dict, List, Optional, Set, Type


class Component:
    """Base class for components (marker)."""


class System:
    """Base class for systems. Override `fixed_update` and/or `update`."""

    def __init__(self) -> None:
        self.world: "World" | None = None

    def on_added(self, world: "World") -> None:
        self.world = world

    def on_removed(self) -> None:
        self.world = None

    def fixed_update(self, dt: float) -> None:  # pragma: no cover - override
        pass

    def update(self, dt: float) -> None:  # pragma: no cover - override
        pass


class World:
    """Lightweight Entity-Component-System (ECS) runtime.

    - Entities are integers generated by the world.
    - Components are arbitrary Python objects keyed by their type.
    - Systems are registered objects with `fixed_update` and/or `update`.
    """

    def __init__(self) -> None:
        self._next_entity_id: int = 1
        self._entities: Set[int] = set()
        self._components: Dict[Type[Any], Dict[int, Any]] = {}
        self._systems: List[System] = []

    def create_entity(self) -> int:
        eid = self._next_entity_id
        self._next_entity_id += 1
        self._entities.add(eid)
        return eid

    def remove_entity(self, entity: int) -> None:
        if entity in self._entities:
            self._entities.remove(entity)
        for comp_map in self._components.values():
            comp_map.pop(entity, None)

    def add_component(self, entity: int, component: Any) -> None:
        comp_type = type(component)
        self._components.setdefault(comp_type, {})[entity] = component

    def remove_component(self, entity: int, comp_type: Type[Any]) -> None:
        comp_map = self._components.get(comp_type)
        if comp_map:
            comp_map.pop(entity, None)

    def get_component(self, entity: int, comp_type: Type[Any]) -> Optional[Any]:
        return self._components.get(comp_type, {}).get(entity)

    def get_components(self, entity: int) -> Dict[Type[Any], Any]:
        out: Dict[Type[Any], Any] = {}
        for t, comp_map in self._components.items():
            if entity in comp_map:
                out[t] = comp_map[entity]
        return out

    def query(self, *component_types: Type[Any]) -> List[int]:
        """Return list of entity ids that have all requested component types."""
        if not component_types:
            return list(self._entities)

        candidates: Optional[Set[int]] = None
        for ct in component_types:
            ents = set(self._components.get(ct, {}).keys())
            if candidates is None:
                candidates = ents
            else:
                candidates &= ents
            if not candidates:
                return []
        return sorted(candidates) if candidates else []

    def register_system(self, system: System) -> None:
        system.on_added(self)
        self._systems.append(system)

    def unregister_system(self, system: System) -> None:
        system.on_removed()
        self._systems.remove(system)

    def fixed_update(self, dt: float) -> None:
        for s in list(self._systems):
            s.fixed_update(dt)

    def update(self, dt: float) -> None:
        for s in list(self._systems):
            s.update(dt)

    def serialize_entity(self, entity: int) -> Dict[str, Any]:
        """Serialize components for an entity.

        Used by editors and save tools; supports dataclasses and plain objects.
        """
        out: Dict[str, Any] = {}
        for t, comp_map in self._components.items():
            c = comp_map.get(entity)
            if c is None:
                continue
            name = t.__name__
            if is_dataclass(c):
                out[name] = asdict(c)
            elif hasattr(c, "__dict__"):
                out[name] = dict(c.__dict__)
            else:
                out[name] = str(c)
        return out
